use super::*;

pub(super) const COMMAND_REGISTRY: &[CommandSpec] = &[
    CommandSpec {
        group: "Discovery",
        name: "help",
        aliases: &[],
        summary: "Show human or JSON help for every CLI command.",
        usage: "bowline help [topic] [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: &[ExampleSpec {
            command: "bowline help agent start --json",
            summary: "Inspect nested help for agent lease creation.",
        }],
        json_output_type: "HelpCommandOutput",
        side_effect_level: "none",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["contract", "version"],
    },
    CommandSpec {
        group: "Discovery",
        name: "version",
        aliases: &["--version"],
        summary: "Print CLI version and protocol compatibility.",
        usage: "bowline version [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "VersionCommandOutput",
        side_effect_level: "none",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["contract"],
    },
    CommandSpec {
        group: "Discovery",
        name: "contract",
        aliases: &[],
        summary: "Print the machine-readable CLI command and output contract.",
        usage: "bowline contract --json",
        options: &[GLOBAL_JSON_OPTION],
        examples: &[ExampleSpec {
            command: "bowline contract --json",
            summary: "Print the machine-readable command contract.",
        }],
        json_output_type: "ContractCommandOutput",
        side_effect_level: "none",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["help", "version"],
    },
    CommandSpec {
        group: "Workspace",
        name: "update",
        aliases: &[],
        summary: "Check for or install the latest Bowline release.",
        usage: "bowline update [--check] [--version <version>] [--json]",
        options: &[
            OptionSpec {
                name: "--check",
                value_name: None,
                summary: "Only check whether an update is available.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--version",
                value_name: Some("version"),
                summary: "Install or check a specific release version.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        examples: &[ExampleSpec {
            command: "bowline update --check --json",
            summary: "Check the install host release manifest.",
        }],
        json_output_type: "UpdateCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["version", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "login",
        aliases: &[],
        summary: "Log in and prepare the local workspace root.",
        usage: "bowline login --root <path> [--headless] [--no-poll]",
        options: &[ROOT_OPTION, GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "LoginCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["logout", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "logout",
        aliases: &[],
        summary: "Clear the saved local account session without removing device trust.",
        usage: "bowline logout [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: &[ExampleSpec {
            command: "bowline logout",
            summary: "Sign this machine out of the current account session.",
        }],
        json_output_type: "LogoutCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["login", "status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "status",
        aliases: &[],
        summary: "Inspect workspace, index, sync, and safe next actions.",
        usage: "bowline status --root <path> [--project <path>] [--watch] [--all] [--json]",
        options: &[
            ROOT_OPTION,
            PROJECT_OPTION,
            OptionSpec {
                name: "--watch",
                value_name: None,
                summary: "Stream status frames.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--all",
                value_name: None,
                summary: "Include retained and archived work status.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        examples: &[ExampleSpec {
            command: "bowline status --root ~/Code --json",
            summary: "Parse the current workspace status.",
        }],
        json_output_type: "StatusCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["actions", "events", "diagnostics collect"],
    },
    CommandSpec {
        group: "Workspace",
        name: "init",
        aliases: &[],
        summary: "Initialize or observe a workspace root.",
        usage: "bowline init --root <path> [--json]",
        options: &[ROOT_OPTION, GLOBAL_JSON_OPTION],
        examples: &[ExampleSpec {
            command: "bowline init --root ~/Code --json",
            summary: "Create or inspect the ~/Code workspace root.",
        }],
        json_output_type: "InitCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["login", "status", "setup"],
    },
    CommandSpec {
        group: "Workspace",
        name: "setup",
        aliases: &[],
        summary: "Prepare a project and report setup receipts.",
        usage: "bowline setup [path] [--yes] [--json]",
        options: &[
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Approve required setup changes.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "PrewarmCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "prewarm",
        aliases: &[],
        summary: "Hydrate and prepare a project path.",
        usage: "bowline prewarm <project> [--approve-setup] [--json]",
        options: &[
            OptionSpec {
                name: "--approve-setup",
                value_name: None,
                summary: "Allow setup receipts when needed.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "PrewarmCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["setup"],
    },
    CommandSpec {
        group: "Workspace",
        name: "actions",
        aliases: &[],
        summary: "Return safe next actions for the current status.",
        usage: "bowline actions --root <path> [--project <path>] [--json]",
        options: &[ROOT_OPTION, PROJECT_OPTION, GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "ActionsCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "search",
        aliases: &[],
        summary: "Search indexed project text with bounded, cursored results.",
        usage: "bowline search <query> [path] [--limit <n>] [--cursor <cursor>] [--path-prefix <prefix>] [--json]",
        options: &[
            LIMIT_OPTION,
            CURSOR_OPTION,
            PATH_PREFIX_OPTION,
            GLOBAL_JSON_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "SearchCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: Some(SEARCH_BOUND),
        related_commands: &["symbols"],
    },
    CommandSpec {
        group: "Workspace",
        name: "symbols",
        aliases: &[],
        summary: "Look up indexed code symbols with bounded, cursored results.",
        usage: "bowline symbols <name> [path] [--limit <n>] [--cursor <cursor>] [--path-prefix <prefix>] [--json]",
        options: &[
            LIMIT_OPTION,
            CURSOR_OPTION,
            PATH_PREFIX_OPTION,
            GLOBAL_JSON_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "SymbolCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: Some(SEARCH_BOUND),
        related_commands: &["search"],
    },
    CommandSpec {
        group: "Workspace",
        name: "explain",
        aliases: &[],
        summary: "Explain path classification, access, and hydration behavior.",
        usage: "bowline explain <path> [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "ExplainCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "events",
        aliases: &[],
        summary: "List recent workspace events.",
        usage: "bowline events --root <path> [--project <path>] [--limit <n>] [--json]",
        options: &[
            ROOT_OPTION,
            PROJECT_OPTION,
            LIMIT_OPTION,
            GLOBAL_JSON_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "EventsCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "resolve",
        aliases: &[],
        summary: "Resolve conflicts or produce agent-ready conflict context.",
        usage: "bowline resolve [path] [--tui|--copy-prompt|--diff <conflict>] [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "ResolveCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Workspace",
        name: "tui",
        aliases: &[],
        summary: "Open the terminal workspace UI.",
        usage: "bowline tui --root <path> [--project <path>]",
        options: &[ROOT_OPTION, PROJECT_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "none",
        side_effect_level: "interactive",
        supports_json: false,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["status"],
    },
    CommandSpec {
        group: "Trust",
        name: "approve",
        aliases: &[],
        summary: "Approve a pending device trust request.",
        usage: "bowline approve --root <path> (--request <id>|--code <matching-code>) [--yes] [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[
            ROOT_OPTION,
            REQUEST_OPTION,
            CODE_OPTION,
            OptionSpec {
                name: "--yes",
                value_name: None,
                summary: "Approve without an interactive prompt.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
            IDEMPOTENCY_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["deny", "revoke", "devices"],
    },
    CommandSpec {
        group: "Trust",
        name: "deny",
        aliases: &[],
        summary: "Deny a pending device trust request.",
        usage: "bowline deny --root <path> (--request <id>|--code <matching-code>) [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[
            ROOT_OPTION,
            REQUEST_OPTION,
            CODE_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
            IDEMPOTENCY_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["approve", "revoke", "devices"],
    },
    CommandSpec {
        group: "Trust",
        name: "revoke",
        aliases: &[],
        summary: "Revoke a trusted device.",
        usage: "bowline revoke --root <path> --device <id> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[
            ROOT_OPTION,
            DEVICE_OPTION,
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
            IDEMPOTENCY_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["approve", "deny", "devices"],
    },
    CommandSpec {
        group: "Trust",
        name: "recover",
        aliases: &[],
        summary: "Manage recovery keys and recovery-based device grants.",
        usage: "bowline recover [status|create|verify <id>|rotate|revoke <id>|use <id>] [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
            RECOVERY_IDEMPOTENCY_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "RecoveryCommandOutput",
        side_effect_level: "mixed",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["approve"],
    },
    CommandSpec {
        group: "Trust",
        name: "devices",
        aliases: &[],
        summary: "List or manage local device records.",
        usage: "bowline devices [request|accept] --root <path> [--request <id>] [--json]",
        options: &[ROOT_OPTION, REQUEST_OPTION, GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DevicesCommandOutput",
        side_effect_level: "mixed",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["approve", "revoke"],
    },
    CommandSpec {
        group: "Trust",
        name: "connect",
        aliases: &[],
        summary: "Install bowline on a remote host and optionally hand off to an agent.",
        usage: "bowline connect <host> [--root <path>] [--project <project> --task <task> --agent <agent>] [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "BootstrapSshCommandOutput",
        side_effect_level: "remote-mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["agent start"],
    },
    CommandSpec {
        group: "Work",
        name: "workon",
        aliases: &[],
        summary: "Create or reuse a named work view for a project.",
        usage: "bowline workon [project] <name> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkonCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["review", "accept", "discard"],
    },
    CommandSpec {
        group: "Work",
        name: "work",
        aliases: &[],
        summary: "List work views.",
        usage: "bowline work [--include-hidden] [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkListCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["workon"],
    },
    CommandSpec {
        group: "Work",
        name: "diff",
        aliases: &[],
        summary: "Show the diff for a work view.",
        usage: "bowline diff <target> [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkDiffCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["review"],
    },
    CommandSpec {
        group: "Work",
        name: "review",
        aliases: &[],
        summary: "Preview whether a work view is ready to accept.",
        usage: "bowline review <target> [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkDiffCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["accept"],
    },
    CommandSpec {
        group: "Work",
        name: "accept",
        aliases: &[],
        summary: "Apply a review-ready work view.",
        usage: "bowline accept <target> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkLifecycleCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["review"],
    },
    CommandSpec {
        group: "Work",
        name: "discard",
        aliases: &[],
        summary: "Discard a work view.",
        usage: "bowline discard <target> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkLifecycleCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["work"],
    },
    CommandSpec {
        group: "Work",
        name: "restore",
        aliases: &[],
        summary: "Restore a discarded work view.",
        usage: "bowline restore <target> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkLifecycleCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["work"],
    },
    CommandSpec {
        group: "Work",
        name: "cleanup",
        aliases: &[],
        summary: "Preview or apply cleanup for retained work views.",
        usage: "bowline cleanup [--apply] [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[
            OptionSpec {
                name: "--apply",
                value_name: None,
                summary: "Apply cleanup instead of previewing it.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
            IDEMPOTENCY_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "WorkCleanupCommandOutput",
        side_effect_level: "conditional-mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["work"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent start",
        aliases: &[],
        summary: "Create an agent lease and return context/prompt commands.",
        usage: "bowline agent start [project] --task <task> [--base <base>] [--hydrate-budget <bytes>] [--work-view] [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[
            OptionSpec {
                name: "--task",
                value_name: Some("task"),
                summary: "Task description for the lease.",
                required: true,
                repeatable: false,
            },
            OptionSpec {
                name: "--base",
                value_name: Some("base"),
                summary: "Lease base, such as latest-workspace or latest:main.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--hydrate-budget",
                value_name: Some("bytes"),
                summary: "Hydration budget reserved for the lease.",
                required: false,
                repeatable: false,
            },
            OptionSpec {
                name: "--work-view",
                value_name: None,
                summary: "Write through an isolated work view.",
                required: false,
                repeatable: false,
            },
            GLOBAL_JSON_OPTION,
            DRY_RUN_OPTION,
            IDEMPOTENCY_OPTION,
        ],
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentLeaseCreateCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["agent context", "agent prompt"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent context",
        aliases: &[],
        summary: "Return full context for an agent lease.",
        usage: "bowline agent context --lease <id> [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentContextCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["agent prompt"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent prompt",
        aliases: &[],
        summary: "Return launch prompt text for an agent lease.",
        usage: "bowline agent prompt --lease <id> [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentPromptCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["agent context"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent publish",
        aliases: &[],
        summary: "Publish agent output for review.",
        usage: "bowline agent publish --lease <id> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentToolResult",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["agent complete"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent complete",
        aliases: &[],
        summary: "Mark an agent lease complete.",
        usage: "bowline agent complete --lease <id> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentToolResult",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["agent publish"],
    },
    CommandSpec {
        group: "Agent",
        name: "agent budget",
        aliases: &[],
        summary: "Grant additional hydration budget to an agent lease.",
        usage: "bowline agent budget --lease <id> --add <bytes> [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "AgentBudgetCommandOutput",
        side_effect_level: "mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["agent context"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon start",
        aliases: &[],
        summary: "Start the local daemon process.",
        usage: "bowline daemon start [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonCommandOutput",
        side_effect_level: "daemon-mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["daemon status"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon stop",
        aliases: &[],
        summary: "Stop the local daemon process.",
        usage: "bowline daemon stop [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonCommandOutput",
        side_effect_level: "daemon-mutation",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["daemon status"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon status",
        aliases: &[],
        summary: "Inspect daemon process and service state.",
        usage: "bowline daemon status [--json]",
        options: &[GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonStatusOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["daemon start", "daemon install"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon install",
        aliases: &[],
        summary: "Install or update the OS service for the daemon.",
        usage: "bowline daemon install [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonServiceOutput",
        side_effect_level: "service-mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["daemon restart", "daemon uninstall"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon restart",
        aliases: &[],
        summary: "Restart the installed daemon service.",
        usage: "bowline daemon restart [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonServiceOutput",
        side_effect_level: "service-mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["daemon install"],
    },
    CommandSpec {
        group: "Daemon",
        name: "daemon uninstall",
        aliases: &[],
        summary: "Uninstall the daemon OS service.",
        usage: "bowline daemon uninstall [--json] [--dry-run] [--idempotency-key <key>]",
        options: &[GLOBAL_JSON_OPTION, DRY_RUN_OPTION, IDEMPOTENCY_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DaemonServiceOutput",
        side_effect_level: "service-mutation",
        supports_json: true,
        supports_dry_run: true,
        supports_idempotency_key: true,
        bounded_output: None,
        related_commands: &["daemon install"],
    },
    CommandSpec {
        group: "Support",
        name: "diagnostics collect",
        aliases: &[],
        summary: "Print a redacted diagnostics bundle.",
        usage: "bowline diagnostics collect --root <path> [--json]",
        options: &[ROOT_OPTION, GLOBAL_JSON_OPTION],
        examples: EMPTY_EXAMPLES,
        json_output_type: "DiagnosticsCollectCommandOutput",
        side_effect_level: "read",
        supports_json: true,
        supports_dry_run: false,
        supports_idempotency_key: false,
        bounded_output: None,
        related_commands: &["status"],
    },
];
