export const COMMAND_NAMES = [
  "help",
  "version",
  "contract",
  "update",
  "unknown",
  "login",
  "logout",
  "approve",
  "deny",
  "revoke",
  "recover",
  "init",
  "setup",
  "prewarm",
  "status",
  "search",
  "symbols",
  "explain",
  "devices",
  "events",
  "actions",
  "tui",
  "resolve",
  "workon",
  "work",
  "diff",
  "review",
  "accept",
  "discard",
  "restore",
  "cleanup",
  "agent start",
  "agent context",
  "agent prompt",
  "agent publish",
  "agent complete",
  "agent budget",
  "daemon start",
  "daemon stop",
  "daemon status",
  "daemon install",
  "daemon restart",
  "daemon uninstall",
  "diagnostics collect",
  "connect",
] as const;
export type CommandName = (typeof COMMAND_NAMES)[number];
